// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA44aTKh9XiWO_LviO2xzSQMzMtbiMcomM',
    appId: '1:301669922840:web:22d36bccd4a0227ded6b6d',
    messagingSenderId: '301669922840',
    projectId: 'social-app-531e5',
    authDomain: 'social-app-531e5.firebaseapp.com',
    storageBucket: 'social-app-531e5.appspot.com',
    measurementId: 'G-5H569JM0M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj0h5wZAGT-TpeerepxPj1_KzDRyj8B6E',
    appId: '1:301669922840:android:cc5d2c6bafa2f846ed6b6d',
    messagingSenderId: '301669922840',
    projectId: 'social-app-531e5',
    storageBucket: 'social-app-531e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfILMjm7XTFRMQtGGa9PzdsNw6hdmwrk',
    appId: '1:301669922840:ios:a9ec1b3e34f2008ced6b6d',
    messagingSenderId: '301669922840',
    projectId: 'social-app-531e5',
    storageBucket: 'social-app-531e5.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfILMjm7XTFRMQtGGa9PzdsNw6hdmwrk',
    appId: '1:301669922840:ios:51df84d3a7e55ac0ed6b6d',
    messagingSenderId: '301669922840',
    projectId: 'social-app-531e5',
    storageBucket: 'social-app-531e5.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
